"""create content_requests table

Revision ID: 2287a06a1f54
Revises: b3663fc8e2c6
Create Date: 2026-04-13 21:07:35.013915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2287a06a1f54'
down_revision: Union[str, Sequence[str], None] = 'b3663fc8e2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_key', sa.String(length=500), nullable=False, comment='Chave no Cloudflare R2'),
    sa.Column('photo_url', sa.String(length=1000), nullable=False, comment='URL pública temporária'),
    sa.Column('source_channel', sa.String(length=50), nullable=False, comment='app | whatsapp | google_drive | dropbox | onedrive'),
    sa.Column('status', sa.Enum('pending', 'analyzing', 'copy', 'design', 'awaiting_approval', 'approved', 'publishing', 'published', 'failed', name='content_status'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output do Agente Analista'),
    sa.Column('copy_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output do Agente Copywriter'),
    sa.Column('design_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output do Agente Designer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_requests_client_id'), 'content_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_content_requests_status'), 'content_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_requests_status'), table_name='content_requests')
    op.drop_index(op.f('ix_content_requests_client_id'), table_name='content_requests')
    op.drop_table('content_requests')
    # ### end Alembic commands ###
